M48
; DRILL file {KiCad 8.0.7-8.0.7-0~ubuntu22.04.1} date 2025-01-11T21:05:42+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-11T21:05:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-8.0.7-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.0201Y-1.5947
X4.2476Y-1.5947
M30
